// Auto-generated by scripts/generate-components.mjs — do not edit manually
import type { ComponentInfo } from "../services/component-registry.js";

export const BUNDLED_COMPONENTS: ComponentInfo[] = [
    {
        "name": "VsAccordion",
        "kebabName": "vs-accordion",
        "description": "A collapsible content panel that shows or hides its content through a toggle interaction."
    },
    {
        "name": "VsAvatar",
        "kebabName": "vs-avatar",
        "description": "A circular or rounded display element for showing user profile images, initials, or icons."
    },
    {
        "name": "VsBar",
        "kebabName": "vs-bar",
        "description": "A full-width horizontal bar component typically used as a header, footer, or toolbar container."
    },
    {
        "name": "VsBlock",
        "kebabName": "vs-block",
        "description": "A content block component with an optional title area and a scrollable content region."
    },
    {
        "name": "VsButton",
        "kebabName": "vs-button",
        "description": "A versatile button component supporting multiple visual variants and a built-in loading state."
    },
    {
        "name": "VsCheckbox",
        "kebabName": "vs-checkbox",
        "description": "A checkbox form input component supporting single and multiple selection modes, with an optional label and validation."
    },
    {
        "name": "VsChip",
        "kebabName": "vs-chip",
        "description": "A compact element for displaying tags, labels, or status indicators with optional icon and close button."
    },
    {
        "name": "VsContainer",
        "kebabName": "vs-container",
        "description": "A layout container component that automatically adjusts its padding when used inside `VsLayout` to accommodate positioned headers, footers, and drawers."
    },
    {
        "name": "VsDimmed",
        "kebabName": "vs-dimmed",
        "description": "A semi-transparent overlay component that covers its parent container with a fade transition."
    },
    {
        "name": "VsDivider",
        "kebabName": "vs-divider",
        "description": "A horizontal or vertical line separator used to visually divide content sections."
    },
    {
        "name": "VsDrawer",
        "kebabName": "vs-drawer",
        "description": "A slide-in panel component that overlays content from any edge of the screen with optional dimmed backdrop and focus trapping."
    },
    {
        "name": "VsExpandable",
        "kebabName": "vs-expandable",
        "description": "A content container with animated expand and collapse transitions controlled by the `open` prop."
    },
    {
        "name": "VsFileDrop",
        "kebabName": "vs-file-drop",
        "description": "A file input component that supports both drag-and-drop and click-to-browse file selection with validation, multiple file support, and form integration."
    },
    {
        "name": "VsFloating",
        "kebabName": "vs-floating",
        "description": "A positioned floating element that renders in a teleport overlay and automatically positions itself relative to a target element with optional animation."
    },
    {
        "name": "VsFocusTrap",
        "kebabName": "vs-focus-trap",
        "description": "A utility component that traps keyboard focus within its single child element, ensuring accessible modal and overlay interactions."
    },
    {
        "name": "VsFooter",
        "kebabName": "vs-footer",
        "description": "A page footer bar component that supports fixed, sticky, and absolute positioning with layout store integration when used inside `VsLayout`."
    },
    {
        "name": "VsForm",
        "kebabName": "vs-form",
        "description": "A form container component that manages validation state and propagates `disabled`/`readonly` states to all child input components."
    },
    {
        "name": "VsGrid",
        "kebabName": "vs-grid",
        "description": "A responsive CSS grid container that supports a configurable number of columns, gap controls, and custom dimensions."
    },
    {
        "name": "VsGroupedList",
        "kebabName": "vs-grouped-list",
        "description": "A scrollable list component that renders items with optional grouping, virtual visibility rendering for performance, and full slot customization."
    },
    {
        "name": "VsHeader",
        "kebabName": "vs-header",
        "description": "A page header bar component that supports fixed, sticky, and absolute positioning with layout store integration when used inside `VsLayout`."
    },
    {
        "name": "VsImage",
        "kebabName": "vs-image",
        "description": "A component for displaying images with support for lazy loading, fallback images, and a skeleton placeholder while loading."
    },
    {
        "name": "VsIndexView",
        "kebabName": "vs-index-view",
        "description": "A container component that shows only the child element at the current index, with optional keep-alive support."
    },
    {
        "name": "VsInnerScroll",
        "kebabName": "vs-inner-scroll",
        "description": "A layout component that provides a scrollable content area with optional sticky header and footer sections."
    },
    {
        "name": "VsInput",
        "kebabName": "vs-input",
        "description": "A feature-rich text input component with validation, clear button, prepend/append slots, and form integration."
    },
    {
        "name": "VsInputWrapper",
        "kebabName": "vs-input-wrapper",
        "description": "A layout wrapper for form inputs that provides a label, validation messages area, and responsive layout support."
    },
    {
        "name": "VsLabelValue",
        "kebabName": "vs-label-value",
        "description": "A two-column display component that pairs a label cell with a value cell, useful for detail views and data tables."
    },
    {
        "name": "VsLayout",
        "kebabName": "vs-layout",
        "description": "A root layout container that provides the layout store context required by `VsHeader`, `VsFooter`, and other layout-aware components."
    },
    {
        "name": "VsLoading",
        "kebabName": "vs-loading",
        "description": "An animated loading indicator composed of five vertical bars with a wave animation."
    },
    {
        "name": "VsMessage",
        "kebabName": "vs-message",
        "description": "A small message display component that shows an icon and text for different UI states: idle, info, success, warning, and error."
    },
    {
        "name": "VsModal",
        "kebabName": "vs-modal",
        "description": "A modal dialog component that renders content in an overlay layer via the Vlossom modal plugin."
    },
    {
        "name": "VsPage",
        "kebabName": "vs-page",
        "description": "A layout component that provides a structured page container with title, description, and content areas."
    },
    {
        "name": "VsPagination",
        "kebabName": "vs-pagination",
        "description": "A pagination component that allows navigation through a series of pages."
    },
    {
        "name": "VsProgress",
        "kebabName": "vs-progress",
        "description": "A progress bar component that displays the completion status of a task."
    },
    {
        "name": "VsRadio",
        "kebabName": "vs-radio",
        "description": "A radio button component (`VsRadio`) and a group component (`VsRadioSet`) for selecting a single option from a list."
    },
    {
        "name": "VsRender",
        "kebabName": "vs-render",
        "description": "A utility component that renders a string (HTML), a Vue component, or a render function as a virtual DOM node."
    },
    {
        "name": "VsResponsive",
        "kebabName": "vs-responsive",
        "description": "A layout wrapper component that applies responsive width and grid column settings based on container breakpoints."
    },
    {
        "name": "VsSearchInput",
        "kebabName": "vs-search-input",
        "description": "A search input component with optional case-sensitive and regex toggle buttons."
    },
    {
        "name": "VsSelect",
        "kebabName": "vs-select",
        "description": "A dropdown select component supporting single and multiple selection with search, grouping, and validation."
    },
    {
        "name": "VsSkeleton",
        "kebabName": "vs-skeleton",
        "description": "A skeleton loading placeholder component that displays an animated background while content is loading."
    },
    {
        "name": "VsSteps",
        "kebabName": "vs-steps",
        "description": "A step indicator component that displays a sequence of steps with progress tracking."
    },
    {
        "name": "VsSwitch",
        "kebabName": "vs-switch",
        "description": "A toggle switch component that supports single and multiple value binding with label customization."
    },
    {
        "name": "VsTable",
        "kebabName": "vs-table",
        "description": "A feature-rich data table component with sorting, searching, pagination, selection, drag-and-drop, and expandable rows."
    },
    {
        "name": "VsTabs",
        "kebabName": "vs-tabs",
        "description": "A tab navigation component with animated indicator, scroll buttons, and vertical layout support."
    },
    {
        "name": "VsTextarea",
        "kebabName": "vs-textarea",
        "description": "A multi-line text input component with validation, string modifiers, and min/max length constraints."
    },
    {
        "name": "VsTextWrap",
        "kebabName": "vs-text-wrap",
        "description": "A container component that wraps text content and provides copy-to-clipboard and external link action buttons."
    },
    {
        "name": "VsThemeButton",
        "kebabName": "vs-theme-button",
        "description": "A toggle button that switches the application between light and dark themes."
    },
    {
        "name": "VsToast",
        "kebabName": "vs-toast",
        "description": "A toast notification component with auto-close, hover pause, and a close button."
    },
    {
        "name": "VsToggle",
        "kebabName": "vs-toggle",
        "description": "A stateful button that toggles between active and inactive states, wrapping `VsButton`."
    },
    {
        "name": "VsTooltip",
        "kebabName": "vs-tooltip",
        "description": "A floating tooltip component that attaches to a target element and supports hover, click, and keyboard interactions."
    },
    {
        "name": "VsVisibleRender",
        "kebabName": "vs-visible-render",
        "description": "A container component that uses IntersectionObserver to track child element visibility and optimize rendering performance."
    }
];
