export enum VsComponent {
    VsAccordion = 'VsAccordion',
    VsAvatar = 'VsAvatar',
    VsBar = 'VsBar',
    VsButton = 'VsButton',
    VsContainer = 'VsContainer',
    VsDivider = 'VsDivider',
    VsExpandable = 'VsExpandable',
    VsFocusTrap = 'VsFocusTrap',
    VsFooter = 'VsFooter',
    VsForm = 'VsForm',
    VsGrid = 'VsGrid',
    VsHeader = 'VsHeader',
    VsImage = 'VsImage',
    VsIndexView = 'VsIndexView',
    VsInnerScroll = 'VsInnerScroll',
    VsLayout = 'VsLayout',
    VsLoading = 'VsLoading',
    VsRender = 'VsRender',
    VsResponsive = 'VsResponsive',
    VsSection = 'VsSection',
    VsSkeleton = 'VsSkeleton',
}
