import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { recordStep, textResponse } from "../utils/mcp-response.js";

const MAX_LABEL_LENGTH = 50;

const choiceSchema = z.object({
    label: z
        .string()
        .describe(`Short display label shown to the user (max ${MAX_LABEL_LENGTH} chars)`),
    prompt: z
        .string()
        .describe("The full prompt to execute if the user selects this option"),
    pipeline: z
        .string()
        .describe(
            "Brief hint of which tools will run, e.g. 'get_component' or 'suggest_components → get_component → generate_component_code'",
        ),
});

export function registerClarifyIntent(server: McpServer): void {
    server.tool(
        "clarify_intent",
        "Call this when you judge the user's intent to be ambiguous — " +
            "i.e. the query could lead to meaningfully different tool pipelines. " +
            "Do not apply a fixed rule; use your own judgment about whether clarification adds value. " +
            "Also call this when a previous tool's _meta.clarify is true. " +
            "Generate exactly 3 candidate interpretations as candidates, each with a distinct pipeline. " +
            "After the server returns choices, present them to the user as numbered options and ask them to pick. " +
            "Once the user picks, execute the chosen prompt as the next query without calling clarify_intent again.",
        {
            query: z.string().describe("The original user query verbatim"),
            candidates: z
                .array(choiceSchema)
                .length(3)
                .describe("Exactly 3 candidate interpretations generated by the AI"),
        },
        async ({ query, candidates }) => {
            const start = Date.now();

            const choices = candidates.map((c, i) => ({
                index: i + 1,
                label:
                    c.label.length > MAX_LABEL_LENGTH
                        ? c.label.slice(0, MAX_LABEL_LENGTH - 1) + "…"
                        : c.label,
                prompt: c.prompt,
                pipeline: c.pipeline,
            }));

            const shortQuery =
                query.length > 24 ? query.slice(0, 23) + "…" : query;
            const meta = recordStep(
                "clarify_intent",
                `Clarify: ${shortQuery}`,
                Date.now() - start,
            );

            return textResponse({ query, choices }, meta);
        },
    );
}
