import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { recordStep, textResponse } from "../utils/mcp-response.js";

const MAX_LABEL_LENGTH = 50;

const choiceSchema = z.object({
    label: z
        .string()
        .describe(`Short display label shown to the user (max ${MAX_LABEL_LENGTH} chars)`),
    prompt: z
        .string()
        .describe("The full prompt to execute if the user selects this option"),
    pipeline: z
        .string()
        .describe(
            "Brief hint of which tools will run, e.g. 'get_component' or 'suggest_components → get_component → generate_component_code'",
        ),
});

export function registerClarifyIntent(server: McpServer): void {
    server.tool(
        "clarify_intent",
        "Call this when the user's query is ambiguous and maps to 3+ equally valid interpretations, " +
            "OR when a previous tool's _meta.clarify is true. " +
            "Generate exactly 3 candidate interpretations as candidates. " +
            "The server validates and returns them as formatted choices to present to the user. " +
            "After the user picks one, execute the corresponding pipeline without calling clarify_intent again.",
        {
            query: z.string().describe("The original user query verbatim"),
            candidates: z
                .array(choiceSchema)
                .length(3)
                .describe("Exactly 3 candidate interpretations generated by the AI"),
        },
        async ({ query, candidates }) => {
            const start = Date.now();

            const choices = candidates.map((c, i) => ({
                index: i + 1,
                label:
                    c.label.length > MAX_LABEL_LENGTH
                        ? c.label.slice(0, MAX_LABEL_LENGTH - 1) + "…"
                        : c.label,
                prompt: c.prompt,
                pipeline: c.pipeline,
            }));

            const shortQuery =
                query.length > 24 ? query.slice(0, 23) + "…" : query;
            const meta = recordStep(
                "clarify_intent",
                `Clarify: ${shortQuery}`,
                Date.now() - start,
            );

            return textResponse({ query, choices }, meta);
        },
    );
}
